### ISSUE TITLE
f5os_lldp_config documentation not clear

### ISSUE THREAD

**Issue by RemcoAA** [F5Networks/f5-ansible-f5os#15]
### Is your feature request related to a problem? Please describe.

The documentation is not clear on how to add multiple interfaces in the configuration.  The documentation states it need to be a dictionary but it is unclear which format is expected for multiple interfaces.
The example also has unsupported parameters (max_core_size, exclude_cores) and for interfaces the parameter is enabled and enable.

### Describe the solution you'd like

Update the documentation with correct examples and an example showing multiple interfaces.

### Describe alternatives you've considered

n/a

### Additional context

n/a

**Comment by pgouband** [comment]
Hi,

Thanks for reporting. Added to the backlog and internal tracking ID for this request is: INFRAANO-1614.

**Comment by RemcoAA** [comment]
@pgouband , thanks for picking this up. Could you already share how multiple interfaces should be added?

**Comment by pgouband** [comment]
Hi @RemcoAA,

Only one interface can be added or modified by this module and it's working as the webui and API so module is working as expected.
Documentation will be updated thanks to your feedback.

```ansible
// Create LLDP
f5os_lldp_config:
    enabled: true
    system_name: "test"
    system_description: "Test Description"
    tx_interval: 31
    tx_hold: 42
    reinitiate_delay: 23
    max_neighbors_per_port: 15
    tx_delay: 22
    interfaces:
      name: 1.0
      enabled: true
      tlv_advertisement_state: "txonly"
      tlv_map: "chassis-id port-id ttl mfs"
    state: present
 
// Update Interface
f5os_lldp_config:
    enabled: true
    system_name: "test"
    system_description: "Test Description"
    tx_interval: 31
    tx_hold: 42
    reinitiate_delay: 24
    max_neighbors_per_port: 15
    tx_delay: 22
    interfaces:
      name: 1.0
      enabled: false
      tlv_advertisement_state: "rxonly"
      tlv_map: "chassis-id port-id ttl"
    state: present
    
 // Add Interface
 f5os_lldp_config:
    enabled: true
    system_name: "test"
    system_description: "Test Description"
    tx_interval: 31
    tx_hold: 42
    reinitiate_delay: 24
    max_neighbors_per_port: 15
    tx_delay: 22
    interfaces:
      name: 2/1.0
      enabled: false
      tlv_advertisement_state: "rxonly"
      tlv_map: "chassis-id port-id ttl"
    state: present
```

**Comment by RemcoAA** [comment]
Hi, then the label "interfaces" is confusing and should be relabeled to "interface"

**Comment by pgouband** [comment]
Hi @RemcoAA,

We are reviewing our options and we will update the issue.

**Comment by MVogel91** [comment]
@RemcoAA 
you could a loop and item configs:

play
```
  tasks:
    - name: Set LLDP
      f5networks.f5os.f5os_lldp_config:
        system_name: "{{ lldp.system_name }}"
        enabled: "{{ lldp.enabled }}"
        interfaces:
          name: "{{ item.name }}"
          enabled: "{{ item.enabled }}"
          tlv_advertisement_state: "{{ item.tlv_advertisement_state }}"
          tlv_map: "chassis-id port-id ttl"
      loop: "{{ lldp.interfaces | flatten(levels=1) }}"
      when: lldp is defined and lldp.interfaces is defined
```

vars:
```
---
lldp:
  system_name: "sysName"
  enabled: true
  interfaces:
    - name: "1.0"
      enabled: true
      tlv_advertisement_state: "txrx"
    - name: "2.0"
      enabled: true
      tlv_advertisement_state: "txonly"
    - name: "3.0"
      enabled: true
      tlv_advertisement_state: "rxonly"
```
with modifications mentioned in https://github.com/F5Networks/f5-ansible-f5os/pull/16/files#diff-eb0419f834a8d1bd56e0acc767386935225d8655e6dfc069d6d3391b8f6943ee
