### ISSUE TITLE
f5os.logging remote_forwarding logs facility not working

### ISSUE THREAD

**Issue by RemcoAA** [F5Networks/f5-ansible-f5os#19]
##### COMPONENT NAME
f5os.logging 

##### ANSIBLE VERSION

```
ansible [core 2.15.9]
  config file = /Users/xxx/Developer/xxx-F5-DO/ansible/ansible.cfg
  configured module search path = ['/Users/xxx/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/xxx/.homebrew/Cellar/ansible@8/8.7.0/libexec/lib/python3.11/site-packages/ansible
  ansible collection location = /Users/xxx/Developer/xxx-F5-DO/ansible/collections/ansible_collections:/usr/share/ansible/collections:/home/ts26ss/py3env01/lib/python3.10/site-packages/ansible_collections
  executable location = /Users/xxx/.homebrew/opt/ansible@8/bin/ansible
  python version = 3.11.9 (main, Apr  2 2024, 08:25:04) [Clang 15.0.0 (clang-1500.3.9.4)] (/Users/xxx/.homebrew/Cellar/ansible@8/8.7.0/libexec/bin/python)
  jinja version = 3.1.3
  libyaml = True
```
##### F5OS VERSION
```
1.7.0-8741
```
##### CONFIGURATION
```
[defaults]
host_key_checking = False
display_skipped_hosts = no
localhost_warning = false
```
##### OS / ENVIRONMENT
N/A

##### SUMMARY
Configuring remote forwarding with log levels gives an error.

##### STEPS TO REPRODUCE
```
- name: Configure Remote Forwarding
  f5os_logging:
    remote_forwarding:
      enabled: true
      logs:
        - facility: local0
          severity: informational
        - facility: authpriv
          severity: notice
        - facility: auth
          severity: emergency
      files:
        - name: ansible.log
        - name: audit/
        - name: boot.log
```

##### EXPECTED RESULTS
Remote forwarding gets configured as specified.

##### ACTUAL RESULTS
```
"msg": "{'ietf-restconf:errors': {'error': [{'error-type': 'application', 'error-tag': 'malformed-message', 'error-path': '/openconfig-system:system/logging/f5-openconfig-system-logging:host-logs/config', 'error-message': 'invalid value for: facility in /system/logging/f5-logging:host-logs/f5-logging:config/f5-logging:selectors/f5-logging:selector/f5-logging:facility'}]}}"
```
