### ISSUE TITLE
Not possible to remove all VLANs from a LAG

### ISSUE THREAD

**Issue by TheStigmj** [F5Networks/f5-ansible-f5os#25]
##### COMPONENT NAME
f5networks.f5os.f5os_lag

##### ANSIBLE VERSION

```
ansible [core 2.15.13]
  config file = None
  configured module search path = ['/home/admin/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/admin/.local/lib/python3.9/site-packages/ansible
  ansible collection location = /home/admin/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/admin/.local/bin/ansible
  python version = 3.9.19 (main, Sep 11 2024, 00:00:00) [GCC 11.5.0 20240719 (Red Hat 11.5.0-2)] (/usr/bin/python3)
  jinja version = 3.1.5
  libyaml = True
```
##### F5OS VERSION
```
1.8.0-17564
```
##### CONFIGURATION

No special settings.
##### OS / ENVIRONMENT

RHEL 9.5
##### SUMMARY

Not possible to remove all VLANs from a LAG.
##### STEPS TO REPRODUCE

```yaml
- name: Testing
  hosts: test
  gather_facts: false
  become: false
  tasks:
    - name: Trunk-vlans on LAG
      f5networks.f5os.f5os_lag:
        name: trunk
        trunk_vlans: [4000]
      register: lag

    - name: Show it
      ansible.builtin.debug:
        var: lag

    - name: Try to remove all Trunk-vlans on LAG
      f5networks.f5os.f5os_lag:
        name: trunk
        trunk_vlans: []
      register: show_lag

    - name: Show it
      ansible.builtin.debug:
        var: show_lag

    - name: Try to show Trunk-vlans on LAG
      f5networks.f5os.f5os_lag:
        name: trunk
        trunk_vlans: null
      register: show_lag2

    - name: Show it
      ansible.builtin.debug:
        var: show_lag2
```

##### EXPECTED RESULTS

1.  Add a new VLAN to the LAG
2. Remove all VLANs from the LAG
3. Attempting to show existing VLANs allowed on the LAG
##### ACTUAL RESULTS

1. The VLAN was added to the LAG replacing all other VLANs
2. Nothing happened (the VLAN remained on the LAG even though a empty list was returned)
3. Nothing happened (the VLAN remained on the LAG and nothing was returned)

```
$ ansible-playbook -i  f5os-inventory test-f5os.yaml -vvv
ansible-playbook [core 2.15.13]
  config file = None
  configured module search path = ['/home/admin/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/admin/.local/lib/python3.9/site-packages/ansible
  ansible collection location = /home/admin/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/admin/.local/bin/ansible-playbook
  python version = 3.9.19 (main, Sep 11 2024, 00:00:00) [GCC 11.5.0 20240719 (Red Hat 11.5.0-2)] (/usr/bin/python3)
  jinja version = 3.1.5
  libyaml = True

PLAYBOOK: test-f5os.yaml **************************************************************************************************************************************************************
1 plays in test-f5os.yaml

PLAY [Testing] ************************************************************************************************************************************************************************

TASK [Trunk-vlans on LAG] *************************************************************************************************************************************************************
task path: /home/admin/ansible/test-f5os.yaml:6
changed: [test] => {
    "changed": true,
    "invocation": {
        "module_args": {
            "config_members": null,
            "interval": null,
            "lag_type": null,
            "mode": null,
            "name": "trunk",
            "native_vlan": null,
            "state": "present",
            "trunk_vlans": [
                4000
            ]
        }
    },
    "trunk_vlans": [
        4000
    ]
}

TASK [Show it] ************************************************************************************************************************************************************************
task path: /home/admin/ansible/test-f5os.yaml:12
ok: [test] => {
    "lag": {
        "changed": true,
        "failed": false,
        "trunk_vlans": [
            4000
        ]
    }
}

TASK [Try to remove all Trunk-vlans on LAG] *******************************************************************************************************************************************
task path: /home/admin/ansible/test-f5os.yaml:16
changed: [test] => {
    "changed": true,
    "invocation": {
        "module_args": {
            "config_members": null,
            "interval": null,
            "lag_type": null,
            "mode": null,
            "name": "trunk",
            "native_vlan": null,
            "state": "present",
            "trunk_vlans": []
        }
    },
    "trunk_vlans": []
}

TASK [Show it] ************************************************************************************************************************************************************************
task path: /home/admin/ansible/test-f5os.yaml:22
ok: [test] => {
    "show_lag": {
        "changed": true,
        "failed": false,
        "trunk_vlans": []
    }
}

TASK [Try to show Trunk-vlans on LAG] *************************************************************************************************************************************************
task path: /home/admin/ansible/test-f5os.yaml:26
ok: [test] => {
    "changed": false,
    "invocation": {
        "module_args": {
            "config_members": null,
            "interval": null,
            "lag_type": null,
            "mode": null,
            "name": "trunk",
            "native_vlan": null,
            "state": "present",
            "trunk_vlans": null
        }
    }
}

TASK [Show it] ************************************************************************************************************************************************************************
task path: /home/admin/ansible/test-f5os.yaml:32
ok: [test] => {
    "show_lag2": {
        "changed": false,
        "failed": false
    }
}

PLAY RECAP ****************************************************************************************************************************************************************************
test                       : ok=6    changed=2    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
```
