### ISSUE TITLE
Unable to get Tenant's configuration state

### ISSUE THREAD

**Issue by mkyrc** [F5Networks/f5-ansible-f5os#32]
### Is your feature request related to a problem? Please describe.
Unable to add new VLANs attached to Tenant without knowledge of previously attached VLANs.

### Describe the solution you'd like
One of the solution can be parameter "add_vlans", e.g.:

```yaml
- name: "F5OS Tenant"
  hosts: "nkt-lb-f5os"
  connection: httpapi
  gather_facts: false

  tasks:

    - name: "01: Update vlans"
      f5networks.f5os.f5os_tenant:
        name: "lab"
        # nodes:
        #   - 1
        add_vlans:
          # - 3000 # existing vlan
          - 3001 # new vlan
```

### Describe alternatives you've considered
Alternative can be get Tenant's state, based on this is possible get current vlan list and then it's possible add new vlan(s) to existing vlans attached to Tenant. Based on this new list of vlan it's possible update the Tenant.

Here is an issue connected to module `f5os_device_info` (https://galaxy.ansible.com/ui/repo/published/f5networks/f5os/content/module/f5os_device_info/), where the result of this module not includes Tenant states. 

If it's possible to add Tenants state to `f5os_device_info` module (or existing `f5os_tenant` module), or build new module e.g. f5os_tenant_state where the result of this module is the list of configured/provisioned/deployed Tenants with configured parameters. I know that API supports this, but ansible module has no support for this informations.

**Comment by mkyrc** [comment]
Thank you @RavinderReddyF5 for response and update. `f5os_device_info` is good place for this. Please include there both - 'state' and 'config' part of JSON response of tenant's information. Thanks.

**Maybe someone helps this workaround**

Currently I'm using workaround based on REST API as an individual task file (it is focused to 'config' only, but in general, there is also 'state' part):

```yaml
- name: "Get Tenant's configuration"
  when:
    - tenant_name is defined
  vars:
    api_base_url: "https://{{ ansible_host }}:{{ ansible_httpapi_port }}"

  ####################
  # get tenant info
  ####################
  block:
    - name: ">GET-TENANT-CFG-01: Get Tenant '{{ tenant_name }}' information (REST API direct call)"
      ansible.builtin.uri:
        url: "{{ api_base_url }}/api/data/f5-tenants:tenants/tenant={{ tenant_name }}/config"
        method: GET
        force_basic_auth: true
        user: "{{ ansible_user }}"
        password: "{{ ansible_httpapi_password }}"
        headers:
          Content-Type: "application/yang-data+json"
          Accept: "application/yang-data+json"
        validate_certs: "{{ ansible_httpapi_validate_certs }}"
        status_code: 200
        return_content: true
        timeout: 60
      register: tenant_info
      check_mode: false
      when:
        - tenant_name is defined
        - ansible_httpapi_validate_certs is defined

    - name: ">GET-TENANT-CFG-02: Show Tenant '{{ tenant_name }}' information"
      ansible.builtin.debug:
        # msg: "F5OS version: {{ f5os_version.json['f5-system-version:version'] }}"
        msg:
          - "{{ tenant_info.json['f5-tenants:config'] }}"
          # - "{{ tenant_info.json }}"
      when:
        - tenant_info is defined
        - tenant_info.json is defined

    - name: ">GET-TENANT-CFG-03: Register Tenant's response"
      ansible.builtin.set_fact:
        tenant_config: "{{ tenant_info.json['f5-tenants:config'] }}"
      when:
        - tenant_info is defined
        - tenant_info.json is defined
        - tenant_info.json['f5-tenants:config'] is defined
 ```
The Tenant's config is registered as `tenant_config` variable. 

Then I can add new vlans to allready configured tenant (nodes and currently configured vlans I'm getting from `tenant_config`). Below is an short example.

```yaml
    - name: "> 02: Add vlans to Tenant '{{ tenant_name }}'"
      f5networks.f5os.f5os_tenant:
        name: "{{ tenant_name }}"
        nodes: "{{ tenant_config.nodes }}"
        vlans: "{{ tenant_config.vlans | union(vlans_add) }}"
      when:
        - tenant_name is defined
        - vlans_add is defined
        - tenant_config is defined
        - tenant_config.vlans is defined
        - tenant_config.nodes is defined
      register: tenant_update
```
