### ISSUE TITLE
Add to the f5os_auth module common LDAP config

### ISSUE THREAD

**Issue by dforste** [F5Networks/f5-ansible-f5os#36]
### Add to the f5os_auth module common LDAP config. I would expect something like the following: 
```
- name: Set Ldap Common Config
  f5os_auth:
    ldap_config:
      base_dn: cn=users,cn=accounts,dc=example,dc=com
      bind_dn: uid=<APPLICATION>,cn=users,cn=accounts,dc=example,dc=com
      bind_pw: <PASSWORD>
      connect_timeout: 0
      read_timeout: 10
      ldap_version: 3
      chase_referrals: true
      tls: Off
      tls_certificate_validation: Demand
      tls_ca_certificate: ....
      cipher_string: ... 
      tls_certificate: ...
      tls_key: ...
      active_directory: false 

```

![Image](https://github.com/user-attachments/assets/72dada94-1870-44ed-ab8b-3c38f7f98939)
